language: ruby
rvm:
  - "1.9.2"
  - "2.0.0"

script: "./bin/linkey check http://www.live.bbc.co.uk/news http://www.live.bbc.co.uk /news a.md "

notifications:
  email:
    recipients:
      - david.blooman@bbc.co.uk
    on_failure: change
    on_success: never
