language: ruby
rvm:
  - "1.9.2"
  - "2.0.0"

script: "./bin/linkey check http://test.on.bbcnewshq.com/news http://test.on.bbcnewshq.com /news news.md "

notifications:
  email:
    recipients:
      - david.blooman@bbc.co.uk
    on_failure: change
    on_success: never
