language: ruby
rvm:
  - "2.0.0"

script: "bundle exec bin/linkey check http://www.bbc.co.uk/arabic http://www.bbc.co.uk /arabic arabic.md"

notifications:
  email:
    recipients:
      - david.blooman@bbc.co.uk
    on_failure: change
    on_success: never
