language: ruby
rvm:
  - "2.0.0"

script: "./bin/linkey check http://www.live.bbc.co.uk/news/world/uk http://www.live.bbc.co.uk /news news.md"

notifications:
  email:
    recipients:
      - david.blooman@bbc.co.uk
    on_failure: change
    on_success: never
