#Headless browser option
browser:
  webkit: "phantomjs"
  # gecko: "slimerjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "lib/linky/javascript/snap.js"

# Type the name of the directory that pages will be stored in
directory:
  - 'pages'

# Add only 2 domains, key will act as a label
domain:
  english: "http://www.live.bbc.co.uk"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  # - 600
  - 1024


#Type page URL paths below, here are a couple of examples
paths:
  home: /news/world
  uk_index: /news/uk
